### PR TITLE
#131 #136 #137

### PR DESCRIPTION
**Pull request by BunsenMcDubbs**

### CODE REVIEW

**Comment by syjer** [comment]
@BunsenMcDubbs thank you for the PR! I'll try to add mysql 5.7 on travis before merging if you don't mind :)

**Comment by BunsenMcDubbs** [comment]
I didn't mean to add to this pull request... I was going to make new PR's but it just automatically went into this one. Hopefully that is ok

**Comment by cbellone** [comment]
don't worry about that, we'll merge it as soon as @syjer will add mysql 5.7 to the test matrix.
For the next PR, please create a new branch from alf.io:master on your fork, so that you can send more "fine-grained" pull requests. 
See https://help.github.com/articles/using-pull-requests/

**Comment by syjer** [comment]
merged :). I'll add later mysql 5.7 in the test matrix, it's a little bit more complicated than expected :)

**Pull request merged**
